ver = 'v 0.1 (alpha)';

f = figure('Name','ATS (alpha v 0.1)','NumberTitle','off','units','normalized');

uiEleme = struct();

%% main UI layout
uiElem.panel_left  = uipanel(f,'Position',[0.10 0.10 0.35 0.60]);
uiElem.panel_right = uipanel(f,'Position',[0.55 0.10 0.35 0.60]);
uiElem.text_title = uicontrol(f,'Style','text','String','Welcome to Airfoil Tool Suite',...
    'Units','normalized','Position',[0.1 0.8 0.8 0.1],...
    'Fontweight','bold','FontSize',14,'FontName','Comic Sans MS');
uiElem.text_author = uicontrol(f,'Style','text','String','Developed by Andrew Mistele (2020)',...
    'Units','normalized','Position',[0.1 0.75 0.8 0.1],...
    'Fontweight','bold','FontSize',10,'FontName','Comic Sans MS');
uiElem.text_version = uicontrol(f,'Style','text','String',ver,...
    'Units','normalized','Position',[0.1 0.7125 0.8 0.1],...
    'Fontweight','bold','FontSize',10,'FontName','Comic Sans MS');

ui.Elem.text_left = uicontrol(f,'Style','text','String','Tools',...
    'Units','normalized','Position',[0.125 0.575 0.3 0.1],...
    'FontWeight','bold','FontSize',12,'FontName','Comic Sans MS');

ui.Elem.text_right = uicontrol(f,'Style','text','String','Airfoils',...
    'Units','normalized','Position',[0.575 0.575 0.3 0.1],...
    'FontWeight','bold','FontSize',12,'FontName','Comic Sans MS');

%% main UI buttons
% left side
uiElem.button_autoXFOIL        = uicontrol(f,'Style','pushbutton','String','autoXFOIL',...
    'Units','normalized','Position',[0.125 0.5 0.3 0.1],...
    'FontWeight','bold','FontSize',10);
uiElem.button_CAMBERUTILS   = uicontrol(f,'Style','pushbutton','String','CamberUtils',...
    'Units','normalized','Position',[0.125 0.375 0.3 0.1],...
    'FontWeight','bold','FontSize',10);
uiElem.button_LERFINDER     = uicontrol(f,'Style','pushbutton','String','LERfinder',...
    'Units','normalized','Position',[0.125 0.250 0.3 0.1],...
    'FontWeight','bold','FontSize',10);
uiElem.button_HELP          = uicontrol(f,'Style','pushbutton','String','Help',...
    'Units','normalized','Position',[0.175 0.125 0.2 0.05],...
    'FontWeight','bold','FontSize',10);

% right side
uiElem.button_LOAD   = uicontrol(f,'Style','pushbutton','String','Load New',...
    'Units','normalized','Position',[0.575  0.125 0.15 0.05],...
    'FontWeight','bold','FontSize',10);
uiElem.button_DELETE = uicontrol(f,'Style','pushbutton','String','Delete',...
    'Units','normalized','Position',[0.725  0.125 0.15 0.05],...
    'FontWeight','bold','FontSize',10);